on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          # Install texml
          sudo apt-get update -y
          sudo sh ./texml.sh
          sudo chmod a+x ./texml/bin/texml
      - run: |
          # run texml
          pdflatex main.tex
          ./texml/bin/texml main.tex
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install & run texml-to-html
        run: | 
          npm install @amermathsoc/texml-to-html
          node ./node_modules/@amermathsoc/texml-to-html/examples/cli.js main.xml > main.html
      - run: |
          # Commit
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: main xml&pdf&html regenerated"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
