on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: xu-cheng/texlive-action@v3
        with:
          os: debian
          run: |
            # Install system dependencies
            apt-get update -y
            sh ./texml.sh
            chmod a+x ./texml/bin/texml
            pdflatex main.tex
            ./texml/bin/texml main.tex
      - run: |
          # Commit
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add main.pdf main.xml
          git commit -m "chore: main.pdf regenerated"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
